// automatically generated by the FlatBuffers compiler, do not modify

package com.bryan.rpc.common.model.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FbsDynamicParam extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static FbsDynamicParam getRootAsFbsDynamicParam(ByteBuffer _bb) { return getRootAsFbsDynamicParam(_bb, new FbsDynamicParam()); }
  public static FbsDynamicParam getRootAsFbsDynamicParam(ByteBuffer _bb, FbsDynamicParam obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FbsDynamicParam __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int value(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int valueLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector valueVector() { return valueVector(new ByteVector()); }
  public ByteVector valueVector(ByteVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer valueAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer valueInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String type() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer typeAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer typeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createFbsDynamicParam(FlatBufferBuilder builder,
      int valueOffset,
      int typeOffset) {
    builder.startTable(2);
    FbsDynamicParam.addType(builder, typeOffset);
    FbsDynamicParam.addValue(builder, valueOffset);
    return FbsDynamicParam.endFbsDynamicParam(builder);
  }

  public static void startFbsDynamicParam(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addValue(FlatBufferBuilder builder, int valueOffset) { builder.addOffset(0, valueOffset, 0); }
  public static int createValueVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createValueVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startValueVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addType(FlatBufferBuilder builder, int typeOffset) { builder.addOffset(1, typeOffset, 0); }
  public static int endFbsDynamicParam(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FbsDynamicParam get(int j) { return get(new FbsDynamicParam(), j); }
    public FbsDynamicParam get(FbsDynamicParam obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

