netty:
  serializer:
    type: PROTOBUF #MESSAGEPACK #KYRO #JDK #HESSIAN #FST #JSON #FLATBUFFERS #THRIFT #PROTOBUF
  server:
    host: localhost
    port: 8082
  registry:
    type: zookeeper
    address: localhost:2181
